name: Test

on:
  push:
    branches: [ '*' ]
    tags: [ '*' ]

jobs:
  build-windows-qt5-package-msi:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Visual Studio Build Tools
        uses: microsoft/setup-msbuild@v1

      - uses: jurplel/install-qt-action@v3
        with:
          version: 6.5.*
          host: windows
          modules: 'qtnetworkauth'

      - run: choco install -y jom

      - uses: egor-tensin/vs-shell@v2
        with:
          arch: x64
          
      - run: Get-Childitem –Path D:\ -Include *qgenericbearer.dll* -Recurse -ErrorAction SilentlyContinue

      - run: Get-Childitem –Path C:\ -Include *qgenericbearer.dll* -Recurse -ErrorAction SilentlyContinue

